name: Unit Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3.1.1
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install etcd
      run: sudo ./.github/install-etcd.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml
